In [2]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:

time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# **Working with Dates**

In [8]:
# Converting to datetime datatype
date['date']=pd.to_datetime(date['date'])

In [10]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

**1.Extract year**

In [11]:
date['date_year'] = date['date'].dt.year

In [12]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

**2.Extract month**

In [13]:
date['date_month_no'] = date['date'].dt.month

In [15]:
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
450 2018-09-30        3532       25       5       2018              9
685 2019-02-28         212       13       1       2019              2
84  2018-07-30        7350       16      76       2018              7
914 2019-08-12        4908       14       4       2019              8
79  2019-05-17         420       26       1       2019              5

In [16]:
date['date_month_name'] = date['date'].dt.month_name()

In [17]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

**3.Extract day**

In [18]:
date['date_day'] = date['date'].dt.day

In [19]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [21]:
date['date_dow_name'] = date['date'].dt.dayofweek

In [22]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,1,1
1,2018-08-15,3646,14,157,2018,8,August,2,2
2,2018-10-23,1859,25,1,2018,10,October,1,1
3,2019-08-17,7292,25,1,2019,8,August,5,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [23]:
date['date_dow_name'] = date['date'].dt.day_name()

In [24]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [25]:
# weekend
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)

In [28]:
date.sample(5)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend
319,2018-07-10,6283,14,2,2018,7,July,1,Tuesday,0
797,2019-03-17,4392,26,8,2019,3,March,6,Sunday,1
26,2019-01-09,6825,16,4,2019,1,January,2,Wednesday,0
495,2018-11-09,7148,16,11,2018,11,November,4,Friday,0
397,2019-06-25,6435,13,1,2019,6,June,1,Tuesday,0

**Extract week of the year**

In [34]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1,1

**Extract quarter**

In [37]:
date['date_quarter'] = date['date'].dt.quarter

In [38]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,date_week,date_quarter
0,2019-12-10,5628,25,3,2019,12,December,1,4,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,2,3,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,1,4,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,5,3,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,1,1,1,1

In [43]:
date['quarter'] = date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,date_week,date_quarter,quarter
0,2019-12-10,5628,25,3,2019,12,December,1,4,0,50,4,4
1,2018-08-15,3646,14,157,2018,8,August,2,3,0,33,3,3
2,2018-10-23,1859,25,1,2018,10,October,1,4,0,43,4,4
3,2019-08-17,7292,25,1,2019,8,August,5,3,1,33,3,3
4,2019-01-06,4344,25,3,2019,1,January,6,1,1,1,1,1

**Extract semester**

In [45]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

In [46]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow_name,date_is_weekend,date_week,date_quarter,quarter,semester
0,2019-12-10,5628,25,3,2019,12,December,1,4,0,50,4,4,2
1,2018-08-15,3646,14,157,2018,8,August,2,3,0,33,3,3,2
2,2018-10-23,1859,25,1,2018,10,October,1,4,0,43,4,4,2
3,2019-08-17,7292,25,1,2019,8,August,5,3,1,33,3,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,1,1,1,1,1,1

**Extract time elaspsed beetween dates**

In [47]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 3, 24, 13, 48, 30, 785076)

In [48]:
today - date['date']

0     2296 days 13:48:30.785076
1     2778 days 13:48:30.785076
2     2709 days 13:48:30.785076
3     2411 days 13:48:30.785076
4     2634 days 13:48:30.785076
                 ...
995   2724 days 13:48:30.785076
996   2665 days 13:48:30.785076
997   2513 days 13:48:30.785076
998   2578 days 13:48:30.785076
999   2352 days 13:48:30.785076
Name: date, Length: 1000, dtype: timedelta64[ns]

In [50]:
(today - date['date']).dt.days

0      2296
1      2778
2      2709
3      2411
4      2634
       ...
995    2724
996    2665
997    2513
998    2578
999    2352
Name: date, Length: 1000, dtype: int64

In [56]:
# month passed
np.round((today - date['date']) / np.timedelta64(1,'D') / 30,0)

0      77.0
1      93.0
2      90.0
3      80.0
4      88.0
       ...
995    91.0
996    89.0
997    84.0
998    86.0
999    78.0
Name: date, Length: 1000, dtype: float64

# **Time**

In [57]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [60]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [61]:
# Convrting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [62]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [64]:
time['hour']  = time['date'].dt.hour
time['min']  = time['date'].dt.minute
time['sec']  = time['date'].dt.second

In [65]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [67]:
# Extract Time part
time['time'] = time['date'].dt.time

In [68]:
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [69]:
# Time defference
today - time['date']

0     4482 days 12:58:30.785076
1     4346 days 14:08:30.785076
2     4832 days 13:27:30.785076
3     4134 days 13:17:30.785076
4     4531 days 14:37:30.785076
                 ...
995   5121 days 12:58:30.785076
996   4442 days 14:34:30.785076
997   4907 days 14:11:30.785076
998   5023 days 14:14:30.785076
999   4295 days 14:23:30.785076
Name: date, Length: 1000, dtype: timedelta64[ns]

In [70]:
# in seconds
(today - time['date']) / np.timedelta64(1,'s')

0      3.872915e+08
1      3.755453e+08
2      4.175333e+08
3      3.572255e+08
4      3.915311e+08
           ...
995    4.425011e+08
996    3.838413e+08
997    4.240159e+08
998    4.340385e+08
999    3.711398e+08
Name: date, Length: 1000, dtype: float64

In [71]:
# in minutes
(today - time['date']) / np.timedelta64(1,'m')

0      6.454859e+06
1      6.259089e+06
2      6.958888e+06
3      5.953758e+06
4      6.525518e+06
           ...
995    7.375019e+06
996    6.397355e+06
997    7.066932e+06
998    7.233975e+06
999    6.185664e+06
Name: date, Length: 1000, dtype: float64

In [73]:
# in hours
(today - time['date']) / np.timedelta64(1,'h')

0      107580.975218
1      104318.141885
2      115981.458551
3       99229.291885
4      108758.625218
           ...
995    122916.975218
996    106622.575218
997    117782.191885
998    120566.241885
999    103094.391885
Name: date, Length: 1000, dtype: float64